apiVersion: v1
kind: Service
metadata:
  name: docask-api-service
spec:
  type: NodePort
  selector:
    app: docask-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31080 # This is the port we opened in your EC2 security group
